apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-auth
type: Opaque
stringData:
  # Kubernetes will automatically Base64 encode these on apply
  username: adminAtish
  password: Admin@mongoexpress
